// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: plugins/services/proto/services.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          *_struct.Struct        `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugins_services_proto_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_services_proto_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugins_services_proto_services_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetArgs() *_struct.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

type StdinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdinRequest) Reset() {
	*x = StdinRequest{}
	mi := &file_plugins_services_proto_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdinRequest) ProtoMessage() {}

func (x *StdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_services_proto_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdinRequest.ProtoReflect.Descriptor instead.
func (*StdinRequest) Descriptor() ([]byte, []int) {
	return file_plugins_services_proto_services_proto_rawDescGZIP(), []int{1}
}

func (x *StdinRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StdoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdoutResponse) Reset() {
	*x = StdoutResponse{}
	mi := &file_plugins_services_proto_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdoutResponse) ProtoMessage() {}

func (x *StdoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_services_proto_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdoutResponse.ProtoReflect.Descriptor instead.
func (*StdoutResponse) Descriptor() ([]byte, []int) {
	return file_plugins_services_proto_services_proto_rawDescGZIP(), []int{2}
}

func (x *StdoutResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_plugins_services_proto_services_proto protoreflect.FileDescriptor

const file_plugins_services_proto_services_proto_rawDesc = "" +
	"\n" +
	"%plugins/services/proto/services.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\":\n" +
	"\vInitRequest\x12+\n" +
	"\x04args\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04args\"\"\n" +
	"\fStdinRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"$\n" +
	"\x0eStdoutResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xdd\x03\n" +
	"\aService\x124\n" +
	"\x04Init\x12\x12.proto.InitRequest\x1a\x16.google.protobuf.Empty\"\x00\x129\n" +
	"\x05Start\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x128\n" +
	"\x04Stop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12;\n" +
	"\aRestart\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12:\n" +
	"\x06Enable\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12;\n" +
	"\aDisable\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x126\n" +
	"\x05Stdin\x12\x13.proto.StdinRequest\x1a\x16.google.protobuf.Empty\"\x00\x129\n" +
	"\x06Stdout\x12\x16.google.protobuf.Empty\x1a\x15.proto.StdoutResponse\"\x00B5Z3github.com/rangertaha/hxe/plugins/services/protob\x06proto3"

var (
	file_plugins_services_proto_services_proto_rawDescOnce sync.Once
	file_plugins_services_proto_services_proto_rawDescData []byte
)

func file_plugins_services_proto_services_proto_rawDescGZIP() []byte {
	file_plugins_services_proto_services_proto_rawDescOnce.Do(func() {
		file_plugins_services_proto_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_services_proto_services_proto_rawDesc), len(file_plugins_services_proto_services_proto_rawDesc)))
	})
	return file_plugins_services_proto_services_proto_rawDescData
}

var file_plugins_services_proto_services_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugins_services_proto_services_proto_goTypes = []any{
	(*InitRequest)(nil),    // 0: proto.InitRequest
	(*StdinRequest)(nil),   // 1: proto.StdinRequest
	(*StdoutResponse)(nil), // 2: proto.StdoutResponse
	(*_struct.Struct)(nil), // 3: google.protobuf.Struct
	(*empty.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_plugins_services_proto_services_proto_depIdxs = []int32{
	3, // 0: proto.InitRequest.args:type_name -> google.protobuf.Struct
	0, // 1: proto.Service.Init:input_type -> proto.InitRequest
	4, // 2: proto.Service.Start:input_type -> google.protobuf.Empty
	4, // 3: proto.Service.Stop:input_type -> google.protobuf.Empty
	4, // 4: proto.Service.Restart:input_type -> google.protobuf.Empty
	4, // 5: proto.Service.Enable:input_type -> google.protobuf.Empty
	4, // 6: proto.Service.Disable:input_type -> google.protobuf.Empty
	1, // 7: proto.Service.Stdin:input_type -> proto.StdinRequest
	4, // 8: proto.Service.Stdout:input_type -> google.protobuf.Empty
	4, // 9: proto.Service.Init:output_type -> google.protobuf.Empty
	4, // 10: proto.Service.Start:output_type -> google.protobuf.Empty
	4, // 11: proto.Service.Stop:output_type -> google.protobuf.Empty
	4, // 12: proto.Service.Restart:output_type -> google.protobuf.Empty
	4, // 13: proto.Service.Enable:output_type -> google.protobuf.Empty
	4, // 14: proto.Service.Disable:output_type -> google.protobuf.Empty
	4, // 15: proto.Service.Stdin:output_type -> google.protobuf.Empty
	2, // 16: proto.Service.Stdout:output_type -> proto.StdoutResponse
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugins_services_proto_services_proto_init() }
func file_plugins_services_proto_services_proto_init() {
	if File_plugins_services_proto_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_services_proto_services_proto_rawDesc), len(file_plugins_services_proto_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_services_proto_services_proto_goTypes,
		DependencyIndexes: file_plugins_services_proto_services_proto_depIdxs,
		MessageInfos:      file_plugins_services_proto_services_proto_msgTypes,
	}.Build()
	File_plugins_services_proto_services_proto = out.File
	file_plugins_services_proto_services_proto_goTypes = nil
	file_plugins_services_proto_services_proto_depIdxs = nil
}
